//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPC_Rental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABOUT
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string About_us { get; set; }
        public string Our_Team { get; set; }
        public string CEO { get; set; }
        public string Decription { get; set; }
    }
}
