// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PPCRental.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("US03_ViewDetails")]
    public partial class US03_ViewDetailsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "US03_ViewDetails.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "US03_ViewDetails", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property Name",
                        "Images",
                        "Street Name",
                        "Price",
                        "Property Type",
                        "District",
                        "Ward",
                        "Street",
                        "City",
                        "Packing Place",
                        "Bed Room",
                        "Bathroom"});
            table1.AddRow(new string[] {
                        "PIS Serviced Apartment – Style 3",
                        "1.jpg",
                        "Đường Nội Bộ TT Chúc Sơn Chương Mỹ",
                        "30000 USD",
                        "Office",
                        "Chương Mỹ",
                        "TT Chúc Sơn",
                        "Đường Nội Bộ",
                        "Hồ Chí Minh",
                        "1",
                        "2",
                        "4"});
#line 7
testRunner.Given("the following projects", ((string)(null)), table1, "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Hien thi chi tiet du an thanh cong")]
        public virtual void HienThiChiTietDuAnThanhCong()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Hien thi chi tiet du an thanh cong", ((string[])(null)));
#line 12
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 13
 testRunner.When("User click \"ID_Project\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Property Name",
                        "Images",
                        "Street Name",
                        "Price",
                        "Property Type",
                        "District",
                        "Ward",
                        "Street",
                        "City",
                        "Packing Place",
                        "Bed Room",
                        "Bathroom"});
            table2.AddRow(new string[] {
                        "PIS Serviced Apartment – Style 3",
                        "1.jpg",
                        "Đường Nội Bộ TT Chúc Sơn Chương Mỹ",
                        "30000 USD",
                        "Office",
                        "Chương Mỹ",
                        "TT Chúc Sơn",
                        "Đường Nội Bộ",
                        "Hồ Chí Minh",
                        "1",
                        "2",
                        "4"});
#line 14
 testRunner.Then("Hien thi thong tin chi tiet du an", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
